services:

    infakt:
        class: Infakt\Infakt
        public: true
        arguments:
            - '%infakt_client.api_key%'
            - '@infakt_client.data_collector_client'

    infakt_client.data_collector_client:
        class: Infakt\ClientBundle\Client\DataCollectorClient
        public: false

    data_collector.infakt:
        class: Infakt\ClientBundle\DataCollector\ClientDataCollector
        arguments:
            - '@infakt_client.data_collector_client'
        public: false
        tags:
            -
                name: data_collector
                id: 'app.infakt_collector'
                template: '@InfaktClient/Collector/infakt.html.twig'

    Infakt\Repository\BankAccountRepository:
        arguments: ['@infakt']
        public: false

    Infakt\Repository\ClientRepository:
        arguments: ['@infakt']
        public: false

    Infakt\Repository\InvoiceRepository:
        arguments: ['@infakt']
        public: false

    Infakt\Repository\VatRateRepository:
        arguments: ['@infakt']
        public: false
